-- BokkuMart Stores Seed
-- Creates/updates store branches based on the schema in app/types/database.types.ts
-- Note: latitude/longitude are set to 0 by default. Update coordinates after import.

INSERT INTO public.stores (
  id,
  name,
  code,
  address,
  city,
  state,
  latitude,
  longitude,
  phone,
  email,
  operating_hours,
  pickup_instructions,
  delivery_radius_km,
  base_delivery_fee,
  per_km_delivery_fee,
  paystack_subaccount_code,
  platform_percentage,
  fixed_commission,
  paystack_settlement_bank_name,
  paystack_settlement_account_number,
  is_active,
  is_flagship,
  is_pilot_branch,
  pilot_mode_enabled,
  delivery_mode,
  features,
  created_at,
  updated_at
)
VALUES
  -- 1) Kosofe / Gbagada / Maryland / Ketu / Ikosi
  (gen_random_uuid(), 'BokkuMart Ketu (Jimoh Balogun)', 'ketu-jimoh-balogun', '23 Jimoh Balogun Street, Ketu, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Gbagada (Phase 1)', 'gbagada-phase-1', '20 Williams Street, Gbagada, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Gbagada (Agidi)', 'gbagada-agidi', '43 Agidi Road, Gbagada, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ogudu', 'ogudu-akinmade', '1 Akinmade Street, Ogudu, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Mende', 'mende-sunny-omeike', '28 Sunny Omeike Street, Mende, Maryland, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Bariga (Abule Okuta)', 'bariga-abule-okuta', '34 Abule Okuta Road, Bariga, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),

  -- 2) Alimosho / Ipaja / Ayobo
  (gen_random_uuid(), 'BokkuMart Ipaja Road 1', 'ipaja-road-1', '49 Ipaja Road, Ipaja, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ipaja Road 2', 'ipaja-road-2', '276 Ipaja Road, Ipaja, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ayobo', 'ayobo-ipaja-ayobo', '264 Ipaja Ayobo Road, Ayobo, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ashipa (Ayobo)', 'ayobo-ashipa', '4 Ashipa Street, Ayobo, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Baruwa', 'baruwa-candos', '55 Candos Road, Baruwa, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Command', 'command-ajasa', '2150 Ajasa Command Road, Command, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Abaranje 1', 'abaranje-1', '153 Abaranje Street, Abaranje, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Abaranje 2', 'abaranje-2', '403 Abaranje Road, Abaranje, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Shasha', 'shasha-orisunbare', '8 Orisunbare Road (Bisiriyu Lawal Street), Shasha, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ijegun (Idimu-Ijegun)', 'ijegun-idimu', 'Idimu-Ijegun Road, Ijegun, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),

  -- 3) Ikeja / Ojodu / Agege
  (gen_random_uuid(), 'BokkuMart Acme (Headquarters)', 'acme-ogba-hq', '7 Acme Road, Ogba, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, true, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Oba Akran', 'oba-akran-ikeja', '20 Oba Akran Avenue, Ikeja, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ogba (Thomas Salako)', 'ogba-thomas-salako', '45 Thomas Salako Street, Ogba, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ojodu Berger 1', 'ojodu-berger-1', '23 Aina Street, Ojodu Berger, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ojodu Berger 2', 'ojodu-berger-2', '115 Aina Street, Ojodu Berger, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Agege (Alfa Nla)', 'agege-alfa-nla', '63 Alfa Nla Road, Agege, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Agege (Capitol)', 'agege-capitol', '52 Capitol Road, Agege, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Fagba', 'fagba-jonathan-coker', '61 Jonathan Coker Road, Fagba, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Iju', 'iju-agbe', '80 Agbe Road, Iju, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Abule Egba', 'abule-egba-ajayi', '72 Ajayi Road, Abule Egba, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Shogunle', 'shogunle-ajisegiri', '26 Ajisegiri Street, Shogunle, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),

  -- 4) Surulere / Mushin / Yaba / Island
  (gen_random_uuid(), 'BokkuMart Surulere (Adeniran)', 'surulere-adeniran-ogunsanya', '41 Adeniran Ogunsanya Street, Surulere, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Surulere (Akpoguma)', 'surulere-akpoguma', '4 Akpoguma Street, Surulere, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ijesha', 'ijesha-ijesha-road', '233 Ijesha Road, Ijesha, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Itire', 'itire-ijesha-road', '82 Ijesha Road, Itire, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Aguda', 'aguda-adetola', '230 Adetola Street, Aguda, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Mushin (Motor Road)', 'mushin-agege-motor', '90 Agege Motor Road, Mushin, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Mushin (Mushin Road)', 'mushin-mushin-road', '42 Mushin Road, Mushin, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ilasamaja', 'ilasamaja-akanro', '17 Akanro Street, Ilasamaja, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Yaba (Sabo)', 'yaba-sabo-herbert', '299 Herbert Macaulay Way, Sabo, Yaba, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Yaba (Adekunle)', 'yaba-adekunle-old-yaba', '52 Old Yaba Road, Adekunle, Yaba, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ebute-Metta', 'ebute-metta-apapa', '135 Apapa Road, Ebute-Metta, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Lagos Island', 'lagos-island-adeniji-adele', '131 Adeniji Adele Road, Lagos Island, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),

  -- 5) Ikorodu / Isolo / Ejigbo
  (gen_random_uuid(), 'BokkuMart Ikorodu (Ayangburen)', 'ikorodu-ayangburen', '88 Ayangburen Road, Ikorodu, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ikorodu (Igbogbo)', 'ikorodu-igbogbo', '117 Oba Molaja Ogunlewe Road, Igbogbo, Ikorodu, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ikorodu (Itamaga)', 'ikorodu-itamaga', 'Off Ijede Road, Itamaga, Ikorodu, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Isolo', 'isolo-kudirat-adenekan', '48A Alh. Kudirat Adenekan Street, Isolo, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ejigbo', 'ejigbo-idimu-ejigbo', '113 Idimu-Ejigbo Road, Ejigbo, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ago Palace', 'ago-palace-way', '120 Ago Palace Way, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),

  -- 6) Ojo / Badagry Expressway / Ajegunle
  (gen_random_uuid(), 'BokkuMart Ajegunle 1', 'ajegunle-1', '61 Ojo Road, Ajegunle, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ajegunle 2', 'ajegunle-2', '230 Ojo Road, Ajegunle, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Alaba Oro', 'alaba-oro', '6 Alaba Oro Road, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Orile Amukoko', 'orile-amukoko-mosafejo', '21 Mosafejo Road, Orile Amukoko, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Orile Gaskiya', 'orile-gaskiya', '68 Gaskiya Road, Orile Gaskiya, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Okokomaiko', 'okokomaiko-ilogbo', '88 Ilogbo Road, Okokomaiko, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Oko Afo', 'oko-afo', 'Oko Afo Road, Oko Afo, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Isashi', 'isashi-aratumi', '101 Aratumi Isashi Road, Isashi, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ijora', 'ijora-ajose', 'Ajose Street, Ijora, Lagos', 'Lagos', 'Lagos State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),

  -- 7) Ogun State & Beyond
  (gen_random_uuid(), 'BokkuMart Arepo', 'arepo', '9 Arepo Road, Arepo, Ogun', 'Ogun', 'Ogun State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Akute/Alagbole', 'akute-alagbole', '100 Alagbole Road, Akute/Alagbole, Ogun', 'Ogun', 'Ogun State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now()),
  (gen_random_uuid(), 'BokkuMart Ibadan (Bodija)', 'ibadan-bodija', 'Bodija Road, Bodija, Ibadan', 'Ibadan', 'Oyo State', 0, 0, null, null,
    '{"monday":{"open":"09:00","close":"21:00","isOpen":true},"tuesday":{"open":"09:00","close":"21:00","isOpen":true},"wednesday":{"open":"09:00","close":"21:00","isOpen":true},"thursday":{"open":"09:00","close":"21:00","isOpen":true},"friday":{"open":"09:00","close":"21:00","isOpen":true},"saturday":{"open":"09:00","close":"21:00","isOpen":true},"sunday":{"open":"09:00","close":"21:00","isOpen":true}}'::jsonb,
    null, 15, 1000, 100, null, null, null, null, null, true, false, false, false, 'automatic', '{}'::jsonb, now(), now())

ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  address = EXCLUDED.address,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  operating_hours = EXCLUDED.operating_hours,
  delivery_radius_km = EXCLUDED.delivery_radius_km,
  base_delivery_fee = EXCLUDED.base_delivery_fee,
  per_km_delivery_fee = EXCLUDED.per_km_delivery_fee,
  is_active = EXCLUDED.is_active,
  is_flagship = EXCLUDED.is_flagship,
  is_pilot_branch = EXCLUDED.is_pilot_branch,
  pilot_mode_enabled = EXCLUDED.pilot_mode_enabled,
  delivery_mode = EXCLUDED.delivery_mode,
  features = EXCLUDED.features,
  updated_at = now();
